title: Human-Centered Privacy Design and Systems
description: Northeastern CS-7375
theme: just-the-docs
color_scheme: blue

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
